# Input
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# Syntax
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.vim/rc/plugins/vim-prettier.rc.vim
'''

# File
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
on_cmd = ['Files']

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_source = ['fzf']
