# Base
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# LSP

# Linter
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  source ~/.vim/rc/plugins/ale.rc.vim
'''

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.vim/rc/plugins/vim-fugitive.rc.vim
'''

# View
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/rc/plugins/lightline.rc.vim
'''

# Theme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
