[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post-update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_signs_enabled = 1
  let g:lsp_diagnostics_echo_cursor = 1
  let g:lsp_signs_error = {'text': '✗'}
  let g:lsp_signs_warning = {'text': '‼'}
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  if !exists('*fugitive#statusline')
    set statusline=%F\ %m%r%h%w%y%{'['.(&fenc!=''?&fenc:&enc).':'.&ff.']'}[L%l/%L,C%03v]
    set statusline+=%=
    set statusline+=%{fugitive#statusline()}
  endif
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    " vim-gitgutter
    let g:gitgutter_sign_added = '✚'
    let g:gitgutter_sign_modified = '➜'
    let g:gitgutter_sign_removed = '✘'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]  # Select then 'S'
repo = 'tpope/vim-surround'

[[plugins]]  # Repead surroud.vim
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]  # HTML tag completion
repo = 'alvan/vim-closetag'

[[plugins]]  # 末尾の全角と半角の空白文字を赤くハイライト
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]  # インデントの可視化
repo = 'Yggdroot/indentLine'

[[plugins]]  # Commentout plugin use 'Ctrl+/(C-_)'
repo = 'tomtom/tcomment_vim'

[[plugins]]  # Show side bar "NERDTree"
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent> <F5> :NERDTreeToggle<CR>'

[[plugins]]  # Session saveing ':Obsession'
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
  ./install --all
'''
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=30<CR>
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

